import os
import sys
import cv2
import torch
import numpy as np
import argparse
import shutil
import json

parser = argparse.ArgumentParser(description="ASpanFormer Keypoint Matching and Image Categorization with JSON input")

parser.add_argument(
    '--json_input_dir', type=str, required=True,
    help='Path to the directory containing JSON files generated by match.py.'
)
parser.add_argument(
    '--output_base_dir', type=str, required=True,
    help='Base directory where output subfolders for each source image will be saved.'
)
parser.add_argument(
    '--breakpoint_value', type=int, required=True,
    help='The breakpoint value for categorizing images based on keypoint matches.'
)
parser.add_argument(
    '--weights_path', type=str, default='./weights/outdoor.ckpt',
    help='Path to the ASpanFormer model weights.'
)
parser.add_argument(
    '--config_path', type=str, default='./ml-aspanformer/configs/aspan/outdoor/aspan_test.py',
    help='Path to the ASpanFormer config file.'
)
parser.add_argument(
    '--long_dim', type=int, default=1024,
    help='Longest dimension to resize images to before matching.'
)
parser.add_argument(
    '--visualize', action='store_true',
    help='If set, save ONLY the visualization image (no target image). Default saves target image only.'
)
parser.add_argument(
    '--full_visualization', action='store_true',
    help='If set, save BOTH the target image AND the visualization image. Overrides --visualize.'
)
parser.add_argument(
    '--skip_low_matches', action='store_true',
    help='If set, completely skip creating folders and saving files for low matches, but still log them.'
)
parser.add_argument(
    '--skip_all', action='store_true',
    help='If set, save NO images'
)
parser.add_argument(
    '--log_filename', type=str, default='match_log.json',
    help='Name of the JSON log file to create in each source image output folder.'
)
parser.add_argument(
    '--aspanpath', type=str, required=True,
    help='Path to the directory containing ml-aspanformer'
)

args = parser.parse_args()
# Add the ml-aspanformer root directory to the system path
sys.path.insert(0, os.path.abspath(args.aspanpath))


from src.ASpanFormer.aspanformer import ASpanFormer
from src.config.default import get_cfg_defaults
from src.utils.misc import lower_config

# --- Helper function for ASpanFormer demo_utils ---
def resize(img, long_dim):
    h, w = img.shape[:2]
    scale = long_dim / max(h, w)
    h_new, w_new = int(round(h * scale)), int(round(w * scale))
    img = cv2.resize(img, (w_new, h_new), interpolation=cv2.INTER_AREA)
    return img

def draw_match(img0, img1, mkpts0, mkpts1):
    H0, W0 = img0.shape[:2]
    H1, W1 = img1.shape[:2]
    H, W = max(H0, H1), W0 + W1
    out = 255 * np.ones((H, W, 3), np.uint8)
    out[:H0, :W0] = img0
    out[:H1, W0:] = img1

    if len(img0.shape) == 2: # Grayscale
        out_rgb = cv2.cvtColor(out, cv2.COLOR_GRAY2BGR)
    else:
        out_rgb = out

    for (x0, y0), (x1, y1) in zip(mkpts0, mkpts1):
        color = tuple(np.random.randint(0, 255, 3).tolist())
        cv2.line(out_rgb, (int(x0), int(y0)), (int(x1) + W0, int(y1)), color, 1)
        cv2.circle(out_rgb, (int(x0), int(y0)), 2, color, -1)
        cv2.circle(out_rgb, (int(x1) + W0, int(y1)), 2, color, -1)

    return out_rgb
# ------------------------------------------------------------------------------------------------

def perform_keypoint_matching(matcher, img0_path, img1_path, long_dim=1024):
    """
    Performs keypoint matching between two images using the ASpanFormer model.
    Returns the filtered keypoints (mkpts0_f, mkpts1_f) and the number of inlier matches.
    """
    img0 = cv2.imread(img0_path)
    img1 = cv2.imread(img1_path)

    if img0 is None or img1 is None:
        print(f"Error: Could not read image {os.path.basename(img0_path)} or {os.path.basename(img1_path)}")
        return None, None, 0 # Return None for filtered keypoints and 0 for count

    img0_g = cv2.imread(img0_path, 0) # Grayscale
    img1_g = cv2.imread(img1_path, 0) # Grayscale

    img0_resized = resize(img0, long_dim)
    img1_resized = resize(img1, long_dim)

    img0_g_resized = resize(img0_g, long_dim)
    img1_g_resized = resize(img1_g, long_dim)

    data = {
        'image0': torch.from_numpy(img0_g_resized / 255.)[None, None].cuda().float(),
        'image1': torch.from_numpy(img1_g_resized / 255.)[None, None].cuda().float()
    }

    with torch.no_grad():
        matcher(data, online_resize=True)
        corr0 = data['mkpts0_f'].cpu().numpy()
        corr1 = data['mkpts1_f'].cpu().numpy()

    #print(f"DEBUG: ASpanFormer detected {len(corr0)} keypoints for pair ({os.path.basename(img0_path)}, {os.path.basename(img1_path)}).")

    # If not enough keypoints, return 0 matches to avoid cv2.error
    if len(corr0) < 8:
        print(f"WARNING: Not enough keypoints ({len(corr0)}) found for image pair ({os.path.basename(img0_path)}, {os.path.basename(img1_path)}) for Fundamental Matrix estimation. Returning (None, None, 0) matches.")
        return None, None, 0 # Return None for filtered keypoints and 0 for count

    try:
        # RANSAC filtering
        F_hat, mask_F = cv2.findFundamentalMat(corr0, corr1, method=cv2.FM_RANSAC, ransacReprojThreshold=1)
        if mask_F is not None:
            mask_F = mask_F[:, 0].astype(bool)
        else:
            mask_F = np.zeros_like(corr0[:, 0]).astype(bool)
        
        # Return filtered keypoints and their count
        return corr0[mask_F], corr1[mask_F], len(corr1[mask_F])
    except cv2.error as e:
        print(f"ERROR: cv2.findFundamentalMat failed for image pair ({os.path.basename(img0_path)}, {os.path.basename(img1_path)}). Returning (None, None, 0). Error: {e}")
        return None, None, 0 # Return None for filtered keypoints and 0 for count

def main():

    # Load ASpanFormer model
    config = get_cfg_defaults()
    config.merge_from_file(args.config_path)
    _config = lower_config(config)
    matcher = ASpanFormer(config=_config['aspan'])
    state_dict = torch.load(args.weights_path, map_location='cpu')['state_dict']
    matcher.load_state_dict(state_dict, strict=False)
    matcher.cuda() # Move model to GPU
    matcher.eval() # Set model to evaluation mode

    os.makedirs(args.output_base_dir, exist_ok=True)

    json_files = [f for f in os.listdir(args.json_input_dir) if f.lower().endswith('.json')]
    total_json_files = len(json_files)
    processed_json_count = 0

    for json_file_name in json_files:
        json_file_path = os.path.join(args.json_input_dir, json_file_name)
        processed_json_count += 1
        print(f"\nProcessing JSON file {processed_json_count}/{total_json_files}: {json_file_name}")

        with open(json_file_path, 'r') as f:
            input_match_data = json.load(f)
        
        source_image_path = input_match_data.get('source')
        if not source_image_path or not os.path.exists(source_image_path):
            print(f"Warning: Source image path not found or invalid in {json_file_name}. Skipping.")
            continue

        source_image_base_name = os.path.splitext(os.path.basename(source_image_path))[0]
        source_output_dir = os.path.join(args.output_base_dir, source_image_base_name)
        os.makedirs(source_output_dir, exist_ok=True)

        # Initialize log data for this source image
        current_source_log = {
            "source_image_path": source_image_path,
            "matches": {}
        }

        high_matches_dir = os.path.join(source_output_dir, 'high_matches')
        low_matches_dir = os.path.join(source_output_dir, 'low_matches')
        
        # Iterate through the matches from the input JSON
        # Assuming input_match_data contains ranked matches directly, e.g., "1": {"filepath": ..., "similarity_score": ...}
        # We need to extract the target filepaths
        target_image_entries = []
        for rank_key, match_info in input_match_data.items():
            if rank_key != "source" and "filepath" in match_info:
                target_image_entries.append(match_info["filepath"])

        print(f"  Processing matches for source: {os.path.basename(source_image_path)}")

        for target_image_path in target_image_entries:
            mkpts0_f, mkpts1_f, num_matches = perform_keypoint_matching(matcher, source_image_path, target_image_path, args.long_dim)
            
            print(f"    Matched {os.path.basename(target_image_path)} with {os.path.basename(source_image_path)}: {num_matches} matches")

            # Add to log regardless of whether files are saved
            current_source_log["matches"][target_image_path] = num_matches

            target_folder_name = 'high_matches' if num_matches >= args.breakpoint_value else 'low_matches'
            target_output_dir = os.path.join(source_output_dir, target_folder_name)

            # Decide if we should save files for this match
            should_save_files = True
            if args.skip_low_matches and target_folder_name == 'low_matches':
                should_save_files = False
                print(f"    Skipping saving low match for {os.path.basename(target_image_path)} due to --skip_low_matches.")
            elif args.skip_all:
                should_save_files = False
                print(f"    Skipping {os.path.basename(target_image_path)} due to --skip_all.")

            if should_save_files:
                os.makedirs(target_output_dir, exist_ok=True) # Ensure high_matches or low_matches dir exists
                output_image_base_name = os.path.splitext(os.path.basename(target_image_path))[0]
                match_result_subfolder = os.path.join(target_output_dir, output_image_base_name)
                os.makedirs(match_result_subfolder, exist_ok=True)

                # Conditional saving based on visualization flags
                if args.full_visualization:
                    # Save both original and visualization
                    shutil.copy(target_image_path, os.path.join(match_result_subfolder, os.path.basename(target_image_path)))
                    if mkpts0_f is not None and len(mkpts0_f) > 0:
                        img0_orig = cv2.imread(source_image_path)
                        img1_orig = cv2.imread(target_image_path)
                        if img0_orig is not None and img1_orig is not None:
                            img0_vis = resize(img0_orig, args.long_dim)
                            img1_vis = resize(img1_orig, args.long_dim)
                            display_matches = draw_match(img0_vis, img1_vis, mkpts0_f, mkpts1_f)
                            visualization_path = os.path.join(match_result_subfolder, f"visualization_{output_image_base_name}.png")
                            cv2.imwrite(visualization_path, display_matches)
                            print(f"      Saved full visualization to {visualization_path}")
                elif args.visualize:
                    # Save only visualization
                    if mkpts0_f is not None and len(mkpts0_f) > 0:
                        img0_orig = cv2.imread(source_image_path)
                        img1_orig = cv2.imread(target_image_path)
                        if img0_orig is not None and img1_orig is not None:
                            img0_vis = resize(img0_orig, args.long_dim)
                            img1_vis = resize(img1_orig, args.long_dim)
                            display_matches = draw_match(img0_vis, img1_vis, mkpts0_f, mkpts1_f)
                            visualization_path = os.path.join(match_result_subfolder, f"visualization_{output_image_base_name}.png")
                            cv2.imwrite(visualization_path, display_matches)
                            print(f"      Saved visualization only to {visualization_path}")
                elif not args.skip_all:
                    # Save only target image (default behavior)
                    shutil.copy(target_image_path, os.path.join(match_result_subfolder, os.path.basename(target_image_path)))
                    print(f"      Saved target image to {match_result_subfolder}")

                print(f"    Categorized {os.path.basename(target_image_path)} to {target_folder_name}/")
                

        # Save the log file for this source image
        log_filepath = os.path.join(source_output_dir, args.log_filename)
        with open(log_filepath, 'w') as f:
            json.dump(current_source_log, f, indent=4)
        print(f"  Saved log file for {os.path.basename(source_image_path)} to {log_filepath}")

    print("Processing complete.")

if __name__ == '__main__':
    main()
